import Head from "next/head";
import { Header, Footer } from "@/layout";
import { GlobalStyle } from "@/styles/globalStyle";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>cooksup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <>
        <GlobalStyle />
        <Header />
        <Component {...pageProps} />
        <Footer />
      </>
    </>
  );
};

export default App;
